name: dart2_fix
author: Dart Team <misc@dartlang.org>
description: A tool to migrate API usage to Dart 2.
homepage: https://github.com/dart-lang/dart2_fix
version: 1.0.1

environment:
  sdk: '>=2.0.0-dev.17.0 <2.0.0'

dependencies:
  analysis_server_lib: ^0.1.4
  analyzer: 0.31.2-alpha.2
  args: ^1.4.0
  cli_util: ^0.1.2
  intl: ^0.15.0
  path: ^1.5.0

dev_dependencies:
  test: ^0.12.0

executables:
  dart2_fix: null
